channels:
  - conda-forge
  - defaults
dependencies:
  - certifi=2019.11.28
  - gdcm=2.8.4
  - glob2=0.7
  - numpy=1.17.2
  - pydicom=1.3.0
  - setuptools=45.1.0
  - tqdm=4.42.0
  - vc=14.1
  - vs2015_runtime=14.16.27012
  - wheel=0.33.6
  - wincertstore=0.2
